---
cache:
  directories:
    - node_modules
install: "npm install"
language: node_js
node_js:
  - node
notifications:
  slack: "lites-team:HDj0ZpIrgLM5vhugukCr7tID"
script:
  - "npm test"
  - gulp
sudo: false
