---
cache:
  directories:
    - node_modules
install: "npm install"
language: node_js
node_js:
  - node
services:
  - docker
notifications:
  slack: "lites-team:HDj0ZpIrgLM5vhugukCr7tID"
script:
  - "npm test"
  - gulp
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t litesteam/website:`git rev-parse --short HEAD` .
  - docker push litesteam/website:`git rev-parse --short HEAD`

sudo: required
